[package]
name = "cargo-generate-rpm"
license = "MIT"
authors = ["@cat_in_136"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "development-tools::build-utils"]
description = "Make a binary RPM package (.rpm) from Cargo projects"
homepage = "https://github.com/cat-in-136/cargo-generate-rpm"
keywords = ["rpm", "package", "cargo", "subcommand"]
repository = "https://github.com/cat-in-136/cargo-generate-rpm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpm-rs = "0.6"
toml = "0.5"
cargo_toml = "0.8"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/cargo-generate-rpm", dest = "/usr/bin/cargo-generate-rpm" },
    { source = "LICENSE", dest = "/usr/share/doc/cargo-generate-rpm/LICENSE", doc = true },
    { source = "README.md", dest = "/usr/share/doc/cargo-generate-rpm/README.md", doc = true }
]
